// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaoymflnwkdiybaciayw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhb3ltZmxud2tkaXliYWNpYXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDYxNTIsImV4cCI6MjA2OTM4MjE1Mn0.v2Kjr0Go14cE4vlhEDlK2Z-Hc2yG8dYU95n2krJGuEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});